version: '3.9'

services:
  server:
    image: server-jo-dev
    container_name: server-jo-dev
    build:
      target: dev
    ports:
      - "3000:3000"
    command: [sh, -c, 'pnpm run start:dev']
    environment:
      - NODE_ENV=development
    env_file:
      - .development.env

  postgres:
    container_name: postgres-jo-dev
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}

  redis:
    container_name: redis-jo-dev
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

