version: '3.9'

services:
  server:
    image: server-jo-dev
    container_name: server-jo-dev
    build:
      target: dev
    command: [sh, -c, 'pnpm run start:dev']
    environment:
      - NODE_ENV=development
    env_file:
      - ./.dev.env

  postgres:
    container_name: postgres-jo-dev
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  redis:
    container_name: redis-jo-dev
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  nginx:
    container_name: nginx-jo-dev
