version: '3.9'

services:
  # SERVER - NESTJS
  server-prod:
    image: server-jo-server-prod
    container_name: server-jo-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: production
    depends_on:
      - postgres-prod
      - redis-prod
    env_file:
      - .prod.env
    environment:
      JWT_ACCESS_TOKEN_SECRET: ${JWT_ACCESS_TOKEN_SECRET}
      JWT_ACCESS_TOKEN_EXPIRATION: ${JWT_ACCESS_TOKEN_EXPIRATION}
      JWT_REFRESH_TOKEN_SECRET: ${JWT_REFRESH_TOKEN_SECRET}
      JWT_REFRESH_TOKEN_EXPIRATION: ${JWT_REFRESH_TOKEN_EXPIRATION}
    volumes:
      - type: volume
        source: pg-data-prod
        target: /var/lib/postgresql/data
    networks:
      - appnet

  # DATABASE - POSTGRESQL
  postgres-prod:
    image: postgres:16-alpine
    container_name: postgres-jo-prod
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: pg-data-prod
        target: /var/lib/postgresql/data
    networks:
      - appnet

  # REDIS - CACHE
  redis-prod:
    image: redis:alpine
    container_name: redis-jo-prod
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - type: volume
        source: redis-data-prod
        target: /data
    networks:
      - appnet

  # API GATEWAY - NGINX
  nginx-prod:
    container_name: nginx-jo-prod
    image: nginx:alpine
    ports:
      #  - "443:443"   # If active HTTPS, also add "443:443"
      - "80:80"
    depends_on:
      - server-prod
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      # - type: bind
      #   source: ./certs
      #   target: /etc/letsencrypt
    networks:
      - appnet

  # certbot-prod:
  #   container_name: certbot-jo-prod
  #   image: certbot/certbot
  #   volumes:
  #     - type: bind
  #       source: ./certbot/conf
  #       target: /etc/letsencrypt
  #     - type: bind
  #       source: ./certbot/www
  #       target: /var/www/certbot
  #   command: certonly --webroot --webroot-path=/var/www/certbot --keep-until-expiring --agree-tos --no-eff-email --email ${CERTBOT_EMAIL} -d ${CERTBOT_DOMAIN} --agree-tos
  #   networks:
  #     - appnet

networks: 
  appnet:

volumes:
  pg-data-prod:  # PERSISTENT VOLUME : db-postgres
  redis-data-prod: # PERSISTENT VOLUME : redis-cache
